fix:rename deliveryURI to remoteDeliveryId
oat-sa/simple-roster pull request #198
Opened 2021-03-02 10:02 UTC by bartlomiejmarszal

On AUT-16 development we realised that there is a mismatch between event attribute name. This PR introduce fix for this issue. 

https://oat-sa.atlassian.net/browse/AUT-16

2021-03-02 10:29 UTC, Skyld requested changes
Just minor comments, thx for the PR 👍  Could you please update the changelog as well?

2021-03-02 10:29 UTC, Skyld commented on docs/docker-development.md
> +$ docker-compose --env-file .env.docker up -d
Could you please revert this?

2021-03-02 13:46 UTC, andreluizmachado requested changes
Hi, Great job by the way. Before proceeding, do not forget:
 - Update the CHANGELOG.md file specifying that the attribute was changed.
 - It would be very king if you could update this doc as well: https://oat-sa.atlassian.net/wiki/spaces/~741679376/pages/775849532/Implementation+Plan+-+Remote+Publication+Simple+Roster+Concept#Suggestion-WebHook-Contract
 -

2021-03-02 18:04 UTC, Skyld requested changes
Please update changelog.md

2021-03-03 08:48 UTC, Skyld approved these changes
- [x] New code is covered by tests
- [x] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues
- [x] Feature is working correctly on my local machine
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Changelog is updated according to changes
- [x] Documentation is updated according to changes

2021-03-03 09:18 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Changelog is updated according to changes (if applicable)
- [x] Documentation is updated according to changes (if applicable)

2021-03-03 09:24 UTC, merged