[RO-357] Phpseclib security vulnerability fix
oat-sa/simple-roster pull request #216
Opened 2021-04-13 11:18 UTC by Skyld

Ticket: https://oat-sa.atlassian.net/browse/RO-357

Fix for: https://github.com/advisories/GHSA-vf4w-fg7r-5v94

2021-04-13 11:38 UTC, luisfn approved these changes
**Review Checklist**
- [X] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful
- [X] Changelog is updated according to changes (if applicable)
- [X] Documentation is updated according to changes (if applicable)

2021-04-19 13:43 UTC, luisfn approved these changes

2021-04-19 16:27 UTC, uncleempty requested changes
Almost there, just a simple comment to discuss :) 
Good job! :+1:

2021-04-19 16:27 UTC, uncleempty commented on src/Security/Generator/JwtTokenGenerator.php
> +            ->canOnlyBeUsedAfter((new DateTimeImmutable())->setTimestamp($currentTime))
Not that it reall matters but could you extract `(new DateTimeImmutable())->setTimestamp($currentTime)` from this line and line 75 into additional variable, please?

2021-04-19 17:01 UTC, uncleempty approved these changes
**Review Checklist**
- [X] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful
- [X] Changelog is updated according to changes (if applicable)
- [X] Documentation is updated according to changes (if applicable)

2021-04-19 18:31 UTC, luisfn approved these changes

2021-04-19 19:57 UTC, merged