Feature/lsi 238 store user generation files to s3
oat-sa/simple-roster pull request #250
Opened 2022-02-07 14:57 UTC by jeethufoc

**Ticket** - https://oat-sa.atlassian.net/browse/LSI-238

**Added** - Store user generation files to S3

2022-02-07 16:24 UTC, SergiiTao requested changes

2022-02-08 08:17 UTC, SergiiTao commented on src/Service/Bulk/BulkCreateUsersService.php
> +        $this->awsS3CsvWriter->writeCsv();
i think it is better to call in the command class itself. 
it is not related to the creation of students

2022-02-08 08:17 UTC, SergiiTao commented on src/Csv/AwsS3CsvWriter.php
> +class AwsS3CsvWriter
and lets rename it to FolderSyncService
and configure it an alias in services, so it can be reused with different parameters

2022-02-10 11:03 UTC, SergiiTao requested changes

2022-02-10 11:03 UTC, SergiiTao commented on config/services.yaml
> +                region: 'eu-west-1'
we shouldn't hardcode the region

2022-02-11 09:16 UTC, SergiiTao requested changes

2022-02-11 09:16 UTC, SergiiTao commented on src/Service/AwsS3/FolderSyncService.php
> +            $this->logger->info($exception->getMessage());
this is an error. so severity should be the error

2022-02-11 09:16 UTC, SergiiTao commented on src/Service/AwsS3/FolderSyncService.php
> +            return $exception->getMessage();
you don't need to return the message. you can throw a new exception right here. better a dedicated one. and catch it later where you want

2022-02-11 09:41 UTC, mianchenia commented on config/services.yaml
> +                    secret: '%env(AWS_S3_ACCESS_SECRET_KEY)%'
Sending AWS key/secret directly is not recommended way to auth. It should be provided by IAM roles inside ec2 instance or ENV variables.
See https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_basic-usage.html

2022-02-11 10:16 UTC, mianchenia commented on src/Service/AwsS3/FolderSyncService.php
> +            $contents = $this->filesystemLocal->listContents(date('Y-m-d'), true);
Path to the folder should be pass as an argument.

2022-02-16 12:57 UTC, mianchenia commented on config/services.yaml
> +            $localUploadsFilesystem: '@oneup_flysystem.default_uploads_filesystem_filesystem'
fixed

2022-02-16 12:58 UTC, mianchenia commented on config/services.yaml
> +                    secret: '%env(AWS_S3_ACCESS_SECRET_KEY)%'
fixed

2022-02-16 12:58 UTC, mianchenia commented on src/Service/AwsS3/FolderSyncService.php
> +            $contents = $this->filesystemLocal->listContents(date('Y-m-d'), true);
fixed

2022-02-21 15:06 UTC, merged