Feature/LSI-1055 Increase automatic user generation performance
oat-sa/simple-roster pull request #275
Opened 2022-08-24 07:06 UTC by jeethufoc

Increase automatic user generation performance

2022-09-12 07:54 UTC, mianchenia commented
Please fix `phpmd` warning.

2022-09-12 08:07 UTC, mianchenia requested changes

2022-09-12 08:07 UTC, mianchenia commented on src/Lti/Service/UserGenerator/UserGeneratorDatabaseStorage.php
> +        UserDtoCollection $userDtoCollection,
We do not need to inject `UserDtoCollection` and `AssignmentDtoCollection`. It would be better to just create them for each `insert...` call.

2022-09-12 08:21 UTC, taorafael commented on src/Lti/Service/UserGenerator/UserGeneratorDatabaseStorage.php
> +                $user->getGroup() ? $user->getGroup() : null
$user->getGroup() ?? null is a cleaner equivalent :)

2022-09-12 08:22 UTC, SergiiTao requested changes

2022-09-12 08:22 UTC, SergiiTao commented on src/Lti/Service/UserGenerator/UserGeneratorDatabaseStorage.php
> +    public function createUserDtoCollection(object $user): void
why it is `public`?

2022-09-12 08:22 UTC, SergiiTao commented on src/Lti/Service/UserGenerator/UserGeneratorDatabaseStorage.php
> +    public function createUserDtoCollection(object $user): void
can we be more specific on the type of $user? `object` seems too generic

2022-09-12 08:22 UTC, SergiiTao commented on src/Lti/Service/UserGenerator/UserGeneratorDatabaseStorage.php
> +                $user->getGroup() ? $user->getGroup() : null
isn't it enough just `$user->getGroup();` ?

2022-09-12 08:22 UTC, SergiiTao commented on src/Repository/NativeAssignmentRepository.php
> +                Carbon::now()->toDateTime()->format('Y-m-d H:i:s')
do we need `Carbon` here?

2022-09-12 08:23 UTC, taorafael commented on src/Lti/Service/UserGenerator/UserGeneratorStateStorageInterface.php
>  }
you might want to include the createUserDtoCollection into the interface as well I guess?

2022-09-12 08:27 UTC, taorafael commented on src/Lti/Service/UserGenerator/UserGeneratorDatabaseStorage.php
>  class UserGeneratorDatabaseStorage implements UserGeneratorStateStorageInterface
The number of objects is breaking the Jenkins pipeline, don't think there's a fix for that other than using less or increasing the limit (which, I believe, won't be the best idea)

2022-09-15 07:25 UTC, SergiiTao requested changes

2022-09-15 07:25 UTC, SergiiTao commented on src/Lti/Service/AssignmentGenerator/AssignmentGeneratorStateStorage.php
> +     *
an extra line

2022-09-15 07:25 UTC, SergiiTao commented on src/Lti/Service/AssignmentGenerator/AssignmentGeneratorStateStorage.php
> +{
it generates nothing and stores nothing. It is rather decorator or mapper...
I am not really sure why do we need it

2022-09-15 11:35 UTC, mianchenia submitted a review, later dismissed

2022-09-15 12:50 UTC, taorafael commented
It seems the pipeline is broken now on the github token:
http://qa.kitchen.it.taocloud.org/blue/organizations/jenkins/Github%20Pull%20Requests%20for%20oat-sa%2Fsimple-roster/detail/PR-275/5/pipeline

2022-09-21 09:12 UTC, SergiiTao approved these changes

2022-09-22 08:03 UTC, mianchenia approved these changes

2023-04-11 08:45 UTC, merged