Feature/LSI 1439 SR switch to php8.1
oat-sa/simple-roster pull request #280
Opened 2022-11-14 08:17 UTC by jeethufoc

Update SR Code to PHP 8.1

2022-11-14 15:47 UTC, mianchenia requested changes
Great job! Please look at my comments. We have to make few updates.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +    private object $jwtConfig;
Please update type hint.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +    private object $jwtInMemoryFilePath;
Please update type hint.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        $this->jwtConfig  = (new ReflectionClass(Configuration::class))->newInstanceWithoutConstructor();
I believe it's not the way we want to use jwt lib. It's not safe to create object with bypassing the constructor.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        $this->jwtInMemoryFilePath = (new ReflectionClass(InMemory::class))->newInstanceWithoutConstructor();
Please look at the comment above.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        return $this->jwtConfig->forAsymmetricSigner(
This is a static method. So we don't need an instance to call it. Please update the call.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +            $this->jwtInMemoryFilePath->file($this->privateKeyPath, $this->passphrase),
This is a static method. Please update the call.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +            $this->jwtInMemoryFilePath->file($this->publicKeyPath, $this->passphrase)
This is a static method. Please update the call.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        $parsedToken =  $this->jwtConfig->forUnsecuredSigner()
This is a static method. Please update the call.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        $key = $this->jwtInMemoryFilePath->file($this->publicKeyPath);
This is a static method. Please update the call.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        $this->jwtInMemoryFilePath = (new ReflectionClass(InMemory::class))->newInstanceWithoutConstructor();
As I see below - we don't really need to create this instances. Please remove them.

2022-11-14 15:47 UTC, mianchenia commented on src/Action/Security/RefreshAccessTokenAction.php
> +            assert($refreshToken instanceof Token\Plain);
Assertions are primary made for debug/develop/test when you want `run or die` scenario.  For business logic is much better to use `if/else`, `throw`, etc. Please replace them.

2022-11-14 15:47 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        assert($parsedToken instanceof Token\Plain);
Assertion. Please replace.

2022-11-14 15:50 UTC, mianchenia commented
There is an error in Jenkins pipeline. Please have a look. Maybe we could fix it.

2022-11-15 14:38 UTC, mianchenia requested changes
Good job! Only one little notice.

2022-11-15 14:38 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        if ($parsedToken instanceof plain) {
It should be in upper case.

2022-11-15 14:38 UTC, mianchenia commented on src/Security/Authenticator/JwtConfiguration.php
> +        if ($parsedToken instanceof plain) {
`Plain`

2022-11-16 08:44 UTC, mianchenia approved these changes, later dismissed

2022-11-17 13:21 UTC, SergiiTao approved these changes

2022-11-17 13:54 UTC, mianchenia approved these changes

2023-02-21 13:12 UTC, jeethufoc commented
Another release branch created to update SR Code to PHP 8.1

2023-02-21 13:12 UTC, closed without merging