Fix/lsi 1561 sr php unit update
oat-sa/simple-roster pull request #283
Opened 2022-12-23 14:04 UTC by jeethufoc

Upgrade Simple Roster PHPUnit Version 
Ticket - [LSI-1561](https://oat-sa.atlassian.net/browse/LSI-1561)

2023-01-05 12:57 UTC, mianchenia requested changes

2023-01-05 12:57 UTC, mianchenia commented on tests/Integration/Security/Verifier/JwtTokenVerifierTest.php
> +        $token = (new ReflectionClass(Plain::class))->newInstanceWithoutConstructor();
Create classes without constructor is a bad practice. Better to use some mock data.

2023-01-06 08:33 UTC, mianchenia approved these changes
LGTM!

2023-01-10 13:26 UTC, SergiiTao commented on tests/Integration/Security/Verifier/JwtTokenVerifierTest.php
> +    private function createToken(): Plain
lets name it like `createNotValidToken` or something. for the better understanding

2023-01-10 13:26 UTC, SergiiTao approved these changes

2023-01-10 13:55 UTC, merged