feat: Add a feature flag for S3 folder sync
oat-sa/simple-roster pull request #287
Opened 2023-02-21 13:07 UTC by jeethufoc

Add a feature flag to enable/disable AWS S3 folder sync while creating QA/LQA users in webhook
Ticket - [LSI-1800](https://oat-sa.atlassian.net/browse/LSI-1800)

2023-02-21 13:50 UTC, SergiiTao commented on src/EventSubscriber/GeneratedUserIngestControllerSubscriber.php
> +        }
early return is good when you want to interrupt a function when something goes wrong or doesn't met some conditions no matter what. but for skipping a single line (even though it's the last one :) I think the classic way is better
```
        if ($this->folderSyncEnabled) {
            $this->userFolderSync->sync($date);
        }
```

2023-02-21 13:53 UTC, SergiiTao requested changes
good job! just 2 minor comments

2023-02-21 13:53 UTC, SergiiTao commented on src/EventSubscriber/GeneratedUserIngestControllerSubscriber.php
> +        bool $folderSyncEnabled
I think the name `isFolderSyncEnabled` is more eloquent

2023-02-21 13:57 UTC, mianchenia requested changes

2023-02-21 13:57 UTC, mianchenia commented on tests/Unit/EventSubscriber/GeneratedUserIngestControllerSubscriberTest.php
> +            false,
How do we check that sync was ignored?

2023-02-21 13:57 UTC, mianchenia commented on tests/Unit/EventSubscriber/GeneratedUserIngestControllerSubscriberTest.php
> +    public function testOnLineItemUpdatedIgnoreOnEmptyList(): void
This test shares same source code that `testOnLineItemUpdatedIgnoreFolderSyncOnDisabled ` does. 
I don't understand how do they test different stuff with the same source code.

2023-02-21 13:58 UTC, mianchenia commented
Good job! Please have a look on my questions.

2023-02-23 09:43 UTC, mianchenia approved these changes
LGTM!

2023-02-23 12:03 UTC, SergiiTao approved these changes

2023-02-24 08:15 UTC, merged